import type { IconComponent } from "@mal-icons/react";
import {
  FiActivity,
  FiArrowRight,
  FiBell,
  FiCalendar,
  FiCamera,
  FiCheck,
  FiCloud,
  FiCode,
  FiDownload,
  FiEdit,
  FiGithub,
  FiGlobe,
  FiHeart,
  FiHome,
  FiLoader,
  FiLock,
  FiMail,
  FiMoon,
  FiSearch,
  FiSettings,
  FiStar,
  FiSun,
  FiTrash2,
  FiUpload,
  FiUser,
  FiZap,
} from "@mal-icons/react/fi";

export const ICONS: ReadonlyArray<readonly [string, IconComponent]> = [
  ["FiActivity", FiActivity],
  ["FiArrowRight", FiArrowRight],
  ["FiBell", FiBell],
  ["FiCalendar", FiCalendar],
  ["FiCamera", FiCamera],
  ["FiCheck", FiCheck],
  ["FiCloud", FiCloud],
  ["FiCode", FiCode],
  ["FiDownload", FiDownload],
  ["FiEdit", FiEdit],
  ["FiGithub", FiGithub],
  ["FiGlobe", FiGlobe],
  ["FiHeart", FiHeart],
  ["FiHome", FiHome],
  ["FiLoader", FiLoader],
  ["FiLock", FiLock],
  ["FiMail", FiMail],
  ["FiMoon", FiMoon],
  ["FiSearch", FiSearch],
  ["FiSettings", FiSettings],
  ["FiStar", FiStar],
  ["FiSun", FiSun],
  ["FiTrash2", FiTrash2],
  ["FiUpload", FiUpload],
  ["FiUser", FiUser],
  ["FiZap", FiZap],
];
